---
# Playbook to deploy Ghost and its components

- name: Deploy cluster
  hosts: localhost
  gather_facts: false
  roles:
      - create_database
      - create_ghost
      - provide_application_info
      - add_admin_user