---
# Playbook to undeploy Ghost and its component
- name: Undeploy Ghost
  hosts: localhost
  gather_facts: false
  roles: 
    - undeploy_database
    - undeploy_ghost
    - role: undeploy_persistent_storage
      when: delete_data is defined and delete_data
