---
# Playbook to undeploy Ghost and its component
- name: Undeploy Ghost
  hosts: localhost
  gather_facts: false
  roles: 
    - undeploy_database
    - undeploy_ghost
    - undeploy_persistent_storage
    - delete_data