---
- name: Deploy MySQL
  kubernetes.core.k8s:
    template: database-deployment.j2
    state: present
  register: database

- name: Create MySQL service
  kubernetes.core.k8s:
    template: database-service.j2
    state: present

- name: Get an existing Service object
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: database-service
    namespace: default
  register: result
  until: "result.resources[0].status.loadBalancer.ingress is defined"
  delay: 60
  retries: 3

- name: Save database ip
  ansible.builtin.set_fact:
    database_ip: '{{ result.resources[0].status.loadBalancer.ingress[0].ip }}'