---
- name: Deploy MySQL
  kubernetes.core.k8s:
    src: database-deployment.yml
    wait: true
    wait_condition:
      type: Running
      status: true
    timeout: 30
    state: present

- name: Create MySQL service
  kubernetes.core.k8s:
    src: database-service.yml
    state: present