---
apiVersion: v1
kind: StorageClass
metadata:
  name: nfs-storage
  namespace: default
provisioner: kubernetes.io/nfs
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-storage
  nfs:
    server: 10.128.0.53
    path: "/mnt/nfs-share"
