---
- name: Delete Persistent Volume
  kubernetes.core.k8s:
    api_version: v1
    kind: PersistentVolume
    name: persistent-volume
    namespace: default
    state: absent

- name: Delete the Database Persistent Volume Claim
  kubernetes.core.k8s:
    api_version: v1
    kind: PersistentVolumeClaim
    name: database-pv-claim
    namespace: default
    state: absent