---
- name: Delete the Ghost deployment
    kubernetes.core.k8s:
      name: ghost
      api_version: apps/v1
      kind: Deployment
      state: absent
  
  - name: Delete the Ghost service
    kubernetes.core.k8s:
      name: ghost-service
      api_version: v1
      kind: Service
      state: absent