apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
