- name: Wait for target NFS server to become reachable/usable
  ansible.builtin.wait_for_connection:
    timeout: 60

- name: Install NFS Server
  package:
    name: nfs-kernel-server
    state: present

- name: Create NFS folder
  ansible.builtin.file:
    path: /mnt/nfs-share
    state: directory

- name: Configure NFS Server
  lineinfile:
   path: /etc/exports
   line: "/mnt/nfs-share *(rw,sync,no_root_squash)"
   state: present

- name: Start NFS server
  service:
    name: nfs-kernel-server
    state: restarted