- name: Delete NFS Server VM
  google.cloud.gcp_compute_instance:
    name: nfs-server
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
  
- name: Delete NFS Server disk
  google.cloud.gcp_compute_disk:
    name: disk-instance
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent