---
apiVersion: v1
kind: PersistentVolumeClaim
namespace: default
metadata:
  name: ghost-pv-claim
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi