---
- name: Delete the MySQL deployment
    kubernetes.core.k8s:
      name: database
      api_version: apps/v1
      kind: Deployment
      state: absent
  
  - name: Delete the MySQL service
    kubernetes.core.k8s:
      name: database-service
      api_version: v1
      kind: Service
      state: absent