---
- name: Delete the MySQL service
  kubernetes.core.k8s:
    api_version: v1
    kind: Service
    name: database-service
    namespace: default
    state: absent

- name: Delete the MySQL deployment
  kubernetes.core.k8s:
    name: database
    api_version: apps/v1
    kind: Deployment
    namespace: default
    state: absent

- name: Delete the database pods
  kubernetes.core.k8s:
    api_version: v1
    kind: Pod
    namespace: default
    label_selectors: 
      - app = database
    state: absent